"""
jurisdiction_map.py -- bidirectional Jurisdiction identifier <-> display name map.

The map is a build-time artifact (jurisdictions.map.json) generated by
concerto-helper.js from the @Display decorators on the Jurisdiction enum in
model.cto. The .cto is the single source of truth; this module just reads the
extracted map at runtime. No Node.js subprocess and no LLM in this path.

Two directions, deliberately asymmetric:

- to_display(identifier): FAIL-CLOSED. An unknown identifier raises ValueError
  so we never render a garbage/unknown jurisdiction into an executed contract.

- to_identifier(display): PASS-THROUGH. An unknown display name is returned
  unchanged, so the schema validator -- not this map -- is the component that
  rejects invalid jurisdictions (e.g. "Mars") with its nicer error message.
"""
from __future__ import annotations

import json
from pathlib import Path

_TEMPLATES_BASE = Path(__file__).resolve().parent.parent / "data" / "templates" / "cicero"

# Cache the forward (identifier -> display) and reverse (display -> identifier)
# maps per template, mirroring schema_validator's schema cache. A forward value
# of None means the template has NO Jurisdiction map (its governingLaw is a plain
# string, not the native enum) -> both directions become identity no-ops.
_forward_cache: dict[str, dict[str, str] | None] = {}
_reverse_cache: dict[str, dict[str, str]] = {}


def _load_maps(template_name: str) -> tuple[dict[str, str] | None, dict[str, str]]:
    """Load and cache the forward + reverse jurisdiction maps for a template.

    Returns (None, {}) for a template that has no jurisdictions.map.json -- only
    templates whose model.cto declares the native Jurisdiction enum (currently
    just nda-mutual) get a map. Non-enum templates need no identifier<->display
    translation, so callers treat a None forward map as identity (no transform).
    """
    if template_name in _forward_cache:
        return _forward_cache[template_name], _reverse_cache.get(template_name, {})

    map_path = _TEMPLATES_BASE / template_name / "jurisdictions.map.json"
    if not map_path.exists():
        _forward_cache[template_name] = None
        _reverse_cache[template_name] = {}
        return None, {}

    forward: dict[str, str] = json.loads(map_path.read_text(encoding="utf-8"))
    # Reverse map derived from the forward map.
    reverse: dict[str, str] = {display: identifier for identifier, display in forward.items()}

    _forward_cache[template_name] = forward
    _reverse_cache[template_name] = reverse
    return forward, reverse


def to_display(identifier: str, template_name: str = "nda-mutual") -> str:
    """Map a Jurisdiction identifier (e.g. "New_York") to its display name.

    FAIL-CLOSED: an unknown identifier raises ValueError. We must never render
    an unrecognized jurisdiction into a contract. Templates with no Jurisdiction
    map (no native enum) have nothing to translate, so the value is returned as-is.
    """
    forward, _ = _load_maps(template_name)
    if forward is None:
        return identifier  # template has no Jurisdiction enum; render verbatim
    if identifier == "OTHER":
        # PR2 abstain sentinel: a valid enum value but NEVER a renderable jurisdiction.
        # Refuse it here so every render path fails closed by construction; callers that
        # need to display the abstention to a human use governingLawRaw, not this.
        raise ValueError(
            "Jurisdiction 'OTHER' is the abstain sentinel and must not be rendered; "
            "a human must supply a supported governing law (see governingLawRaw)."
        )
    if identifier not in forward:
        raise ValueError(
            f"Unknown jurisdiction identifier: {identifier!r} "
            f"(template {template_name!r}). Valid identifiers come from the "
            f"Jurisdiction enum in model.cto."
        )
    return forward[identifier]


def to_identifier(display: str, template_name: str = "nda-mutual") -> str:
    """Map a Jurisdiction display name (e.g. "New York") to its identifier.

    PASS-THROUGH: an unknown display name is returned unchanged so the schema
    validator is the component that rejects invalid jurisdictions. Templates with
    no Jurisdiction map (no native enum) need no normalization -> value as-is.
    """
    forward, reverse = _load_maps(template_name)
    if forward is None:
        return display  # template has no Jurisdiction enum; no normalization
    return reverse.get(display, display)


def known_identifiers(template_name: str = "nda-mutual") -> set[str]:
    """The set of REPRESENTABLE Jurisdiction enum identifiers for a template (empty if
    the template has no native Jurisdiction enum). EXCLUDES the OTHER abstain sentinel,
    which is a valid enum value but NOT a real jurisdiction -- used by the intent gate
    to test whether a requested jurisdiction is representable at all, so it must never
    treat OTHER as representable."""
    forward, _ = _load_maps(template_name)
    return (set(forward.keys()) - {"OTHER"}) if forward else set()


def resolve_to_identifier(value: str, template_name: str = "nda-mutual"):
    """Strict, CASE-INSENSITIVE resolution: map a display name OR identifier to its
    enum identifier, or return None if it is not a known jurisdiction. Unlike
    to_identifier (exact + pass-through), this is what the intent gate needs to test
    representability without false-flagging casual casing ("new york" -> New_York).
    Returns None for the OTHER abstain sentinel -- it is not a resolvable jurisdiction."""
    if (value or "").strip().upper() == "OTHER":
        return None
    forward, reverse = _load_maps(template_name)
    if forward is None:
        return None
    if value in forward:
        return value
    if value in reverse:
        return reverse[value]
    low = (value or "").strip().lower()
    if not low:
        return None
    for ident, disp in forward.items():
        if ident.lower() == low or disp.lower() == low:
            return ident
    return None


# ---------------------------------------------------------------------------
# General per-enum display mapping (cross-field replication, 2026-06).
# Mirrors the Jurisdiction map for ANY @Display-bearing enum (EntityType,
# DisputeForum, ...) via the generated enum-displays.map.json.
# ---------------------------------------------------------------------------
_enum_cache: dict[tuple[str, str], tuple[dict[str, str] | None, dict[str, str]]] = {}


def _load_enum_map(template_name: str, enum_name: str):
    """Load + cache (forward id->display, reverse display->id) for one enum from
    enum-displays.map.json. Returns (None, {}) if the file or enum is absent."""
    key = (template_name, enum_name)
    if key in _enum_cache:
        return _enum_cache[key]
    path = _TEMPLATES_BASE / template_name / "enum-displays.map.json"
    if not path.exists():
        _enum_cache[key] = (None, {})
        return _enum_cache[key]
    doc = json.loads(path.read_text(encoding="utf-8"))
    forward = doc.get(enum_name)
    if not isinstance(forward, dict):
        _enum_cache[key] = (None, {})
        return _enum_cache[key]
    # RT7 runtime backstop (codegen also validates): a display-string collision would
    # silently last-win in the reverse map and misattribute one member's display to
    # another identifier. Fail loud instead.
    reverse: dict[str, str] = {}
    for ident, disp in forward.items():
        if disp in reverse:
            raise ValueError(
                f"enum-displays.map.json: enum {enum_name!r} (template {template_name!r}) "
                f"has a display-string collision: members {reverse[disp]!r} and {ident!r} "
                f"both display as {disp!r}. Fix the @Display decorators and regenerate."
            )
        reverse[disp] = ident
    _enum_cache[key] = (forward, reverse)
    return _enum_cache[key]


def to_display_enum(enum_name: str, value: str, template_name: str = "nda-mutual") -> str:
    """Map an enum identifier (e.g. "limited_liability_company") to its display name
    ("limited liability company"). Accepts an already-display value (returned as-is).
    FAIL-CLOSED: an unknown value raises ValueError (never render an unrecognized
    enum value). Templates without the map return the value verbatim."""
    forward, reverse = _load_enum_map(template_name, enum_name)
    if forward is None:
        return value
    if value in forward:
        return forward[value]
    if value in reverse:  # already a display name
        return value
    raise ValueError(
        f"Unknown {enum_name} value: {value!r} (template {template_name!r}); "
        f"not an identifier or display name in enum-displays.map.json."
    )


def to_identifier_enum(enum_name: str, value: str, template_name: str = "nda-mutual") -> str:
    """Map an enum display name (or identifier) to its identifier. Pass-through for an
    unknown value (the schema validator is the gatekeeper), mirroring to_identifier."""
    forward, reverse = _load_enum_map(template_name, enum_name)
    if forward is None:
        return value
    if value in forward:
        return value
    if value in reverse:
        return reverse[value]
    return value


def clear_cache() -> None:
    """Clear the jurisdiction + general enum map caches (useful in tests)."""
    _forward_cache.clear()
    _reverse_cache.clear()
    _enum_cache.clear()
